var N = null;var sourcesIndex = {};
sourcesIndex["anyhow"] = {"name":"","files":["backtrace.rs","chain.rs","context.rs","error.rs","fmt.rs","kind.rs","lib.rs","macros.rs","wrapper.rs"]};
sourcesIndex["approx"] = {"name":"","files":["abs_diff_eq.rs","lib.rs","macros.rs","relative_eq.rs","ulps_eq.rs"]};
sourcesIndex["enum_primitive_derive"] = {"name":"","files":["lib.rs"]};
sourcesIndex["geo_types"] = {"name":"","files":["coordinate.rs","geometry.rs","geometry_collection.rs","lib.rs","line.rs","line_string.rs","macros.rs","multi_line_string.rs","multi_point.rs","multi_polygon.rs","point.rs","polygon.rs","private_utils.rs","rect.rs","triangle.rs"]};
sourcesIndex["geojson"] = {"name":"","files":["feature.rs","feature_collection.rs","geojson.rs","geometry.rs","lib.rs","util.rs"]};
sourcesIndex["itoa"] = {"name":"","files":["lib.rs"]};
sourcesIndex["libc"] = {"name":"","dirs":[{"name":"unix","dirs":[{"name":"linux_like","dirs":[{"name":"linux","dirs":[{"name":"gnu","dirs":[{"name":"b64","dirs":[{"name":"x86_64","files":["align.rs","mod.rs","not_x32.rs"]}],"files":["mod.rs"]}],"files":["align.rs","mod.rs"]}],"files":["align.rs","mod.rs"]}],"files":["mod.rs"]}],"files":["align.rs","mod.rs"]}],"files":["fixed_width_ints.rs","lib.rs","macros.rs"]};
sourcesIndex["num_traits"] = {"name":"","files":["lib.rs"]};
sourcesIndex["quote"] = {"name":"","files":["ident.rs","lib.rs","to_tokens.rs","tokens.rs"]};
sourcesIndex["ryu"] = {"name":"","dirs":[{"name":"buffer","files":["mod.rs"]},{"name":"pretty","files":["exponent.rs","mantissa.rs","mod.rs"]}],"files":["common.rs","d2s.rs","d2s_full_table.rs","d2s_intrinsics.rs","digit_table.rs","f2s.rs","f2s_intrinsics.rs","lib.rs"]};
sourcesIndex["serde"] = {"name":"","dirs":[{"name":"de","files":["from_primitive.rs","ignored_any.rs","impls.rs","mod.rs","utf8.rs","value.rs"]},{"name":"private","files":["de.rs","macros.rs","mod.rs","ser.rs"]},{"name":"ser","files":["fmt.rs","impls.rs","impossible.rs","mod.rs"]}],"files":["export.rs","integer128.rs","lib.rs","macros.rs"]};
sourcesIndex["serde_json"] = {"name":"","dirs":[{"name":"features_check","files":["mod.rs"]},{"name":"io","files":["mod.rs"]},{"name":"value","files":["de.rs","from.rs","index.rs","mod.rs","partial_eq.rs","ser.rs"]}],"files":["de.rs","error.rs","iter.rs","lib.rs","macros.rs","map.rs","number.rs","read.rs","ser.rs"]};
sourcesIndex["sfcgal"] = {"name":"","dirs":[{"name":"conversion","files":["coords.rs","geojson.rs","geotypes.rs","macros.rs","mod.rs"]}],"files":["errors.rs","geometry.rs","lib.rs","utils.rs"]};
sourcesIndex["sfcgal_sys"] = {"name":"","files":["lib.rs"]};
sourcesIndex["syn"] = {"name":"","files":["attr.rs","constant.rs","data.rs","derive.rs","escape.rs","generics.rs","ident.rs","lib.rs","lit.rs","mac.rs","op.rs","ty.rs"]};
sourcesIndex["synom"] = {"name":"","files":["helper.rs","lib.rs","space.rs"]};
sourcesIndex["unicode_xid"] = {"name":"","files":["lib.rs","tables.rs"]};
createSourceSidebar();
